CREATE TABLE CLIENTE (
	
	 ID INT  PRIMARY KEY AUTO_INCREMENT,
	 CLIENTE VARCHAR(100)
	
);

CREATE TABLE PRODUTO (
	
	 ID INT  PRIMARY KEY AUTO_INCREMENT,
	 DESCRICAO_PRODUTO VARCHAR(100),
	 PRECO_UNITARIO NUMERIC(20,2)
	
);


CREATE TABLE PEDIDO (
	
	 ID INT  PRIMARY KEY AUTO_INCREMENT,
	 CILENTE_ID NUMBER REFERENCES CLIENTE (ID),
	 DATA_PEDIDO TIMESTAMP,
	 TOTAL NUMERIC(10,2)
	
);

CREATE TABLE ITEM_PEDIDO (
	
	 ID INT  PRIMARY KEY AUTO_INCREMENT,
	 PEDIDO_ID NUMBER REFERENCES PEDIDO (ID),
	 PRODUTO_ID NUMBER REFERENCES PRODUTO (ID),
	 QUANTIDADE NUMBER
	
);